# Generated by Django 4.1.3 on 2023-07-06 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_coins', models.IntegerField(blank=True, null=True)),
                ('silver_coins', models.IntegerField(blank=True, null=True)),
                ('copper_coins', models.IntegerField(blank=True, null=True)),
                ('electron_coins', models.IntegerField(blank=True, null=True)),
                ('platinum_coins', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrobatics_active', models.BooleanField(default=False)),
                ('acrobatics', models.IntegerField(blank=True, null=True)),
                ('anim_handling_active', models.BooleanField(default=False)),
                ('anim_handling', models.IntegerField(blank=True, null=True)),
                ('arcana_active', models.BooleanField(default=False)),
                ('arcana', models.IntegerField(blank=True, null=True)),
                ('athletics_active', models.BooleanField(default=False)),
                ('athletics', models.IntegerField(blank=True, null=True)),
                ('deception_active', models.BooleanField(default=False)),
                ('deception', models.IntegerField(blank=True, null=True)),
                ('history_active', models.BooleanField(default=False)),
                ('history', models.IntegerField(blank=True, null=True)),
                ('insight_active', models.BooleanField(default=False)),
                ('insight', models.IntegerField(blank=True, null=True)),
                ('intimidation_active', models.BooleanField(default=False)),
                ('intimidation', models.IntegerField(blank=True, null=True)),
                ('investigation_active', models.BooleanField(default=False)),
                ('investigation', models.IntegerField(blank=True, null=True)),
                ('medicine_active', models.BooleanField(default=False)),
                ('medicine', models.IntegerField(blank=True, null=True)),
                ('nature_active', models.BooleanField(default=False)),
                ('nature', models.IntegerField(blank=True, null=True)),
                ('perception_active', models.BooleanField(default=False)),
                ('perception', models.IntegerField(blank=True, null=True)),
                ('performance_active', models.BooleanField(default=False)),
                ('performance', models.IntegerField(blank=True, null=True)),
                ('persuasion_active', models.BooleanField(default=False)),
                ('persuasion', models.IntegerField(blank=True, null=True)),
                ('religion_active', models.BooleanField(default=False)),
                ('religion', models.IntegerField(blank=True, null=True)),
                ('sleight_of_hand_active', models.BooleanField(default=False)),
                ('sleight_of_hand', models.IntegerField(blank=True, null=True)),
                ('stealth_active', models.BooleanField(default=False)),
                ('stealth', models.IntegerField(blank=True, null=True)),
                ('survival_active', models.BooleanField(default=False)),
                ('survival', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterViewsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_traits', models.TextField(blank=True)),
                ('ideals', models.TextField(blank=True)),
                ('bonds', models.TextField(blank=True)),
                ('flaws', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModificationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('dexterity', models.IntegerField(blank=True, null=True)),
                ('constitution', models.IntegerField(blank=True, null=True)),
                ('intelligence', models.IntegerField(blank=True, null=True)),
                ('wisdom', models.IntegerField(blank=True, null=True)),
                ('charisma', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingThrowsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_sb_active', models.BooleanField(default=False)),
                ('strength_sb', models.IntegerField(blank=True, null=True)),
                ('dexterity_sb_active', models.BooleanField(default=False)),
                ('dexterity_sb', models.IntegerField(blank=True, null=True)),
                ('constitution_sb_active', models.BooleanField(default=False)),
                ('constitution_sb', models.IntegerField(blank=True, null=True)),
                ('intelligence_sb_active', models.BooleanField(default=False)),
                ('intelligence_sb', models.IntegerField(blank=True, null=True)),
                ('wisdom_sb_active', models.BooleanField(default=False)),
                ('wisdom_sb', models.IntegerField(blank=True, null=True)),
                ('charisma_sb_active', models.BooleanField(default=False)),
                ('charisma_sb', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('level', models.IntegerField(default=-1)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('weapon_type', models.CharField(default='Uncategorized', max_length=32, verbose_name='Weapon Type')),
                ('rarity', models.CharField(default='Uncategorized', max_length=32, verbose_name='Rarity')),
                ('weigth', models.IntegerField(default=-1)),
                ('weapon_category', models.CharField(default='Uncategorized', max_length=32)),
                ('weapon_range', models.CharField(default=-1, max_length=32)),
                ('dmg_type', models.CharField(default='Uncategorized', max_length=32)),
                ('dmg1', models.CharField(default='-1', max_length=32)),
                ('dmg2', models.CharField(default='-1', max_length=32)),
                ('bonus_weapon', models.CharField(default='-1', max_length=32)),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapon',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_img', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('heroes_class', models.CharField(blank=True, max_length=200)),
                ('background', models.CharField(blank=True, max_length=200)),
                ('race', models.CharField(blank=True, max_length=200)),
                ('alignment', models.CharField(blank=True, max_length=200)),
                ('exp_points', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('inspiration', models.BooleanField(default=False)),
                ('prof_bonus', models.IntegerField(blank=True, null=True)),
                ('armor_class', models.CharField(blank=True, max_length=10)),
                ('initiative', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('hit_points', models.IntegerField(blank=True, null=True)),
                ('max_hit_points', models.IntegerField(blank=True, null=True)),
                ('temporary_hit_points', models.IntegerField(blank=True, null=True)),
                ('hit_dice', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('death_successes', models.IntegerField(blank=True, null=True)),
                ('death_failures', models.IntegerField(blank=True, null=True)),
                ('other_profs_and_langs', models.TextField(blank=True)),
                ('passive_wisdom', models.IntegerField(blank=True, null=True)),
                ('attacks_and_spellcasting', models.ManyToManyField(blank=True, to='heroes.spell')),
                ('char_money', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.charactermoney')),
                ('char_views', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.characterviewsset')),
                ('equipment', models.ManyToManyField(blank=True, to='heroes.item')),
                ('features_and_traits', models.ManyToManyField(blank=True, to='heroes.feature')),
                ('modifications_set', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.modificationset')),
                ('saving_throws_set', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.savingthrowsset')),
                ('skills_set', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.characterskills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weapons', models.ManyToManyField(blank=True, to='heroes.weapon')),
            ],
        ),
    ]
