# Generated by Django 4.1.3 on 2022-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_hero_acrobatics_alter_hero_anim_handling_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Герой', 'verbose_name_plural': 'Герои'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Оружие', 'verbose_name_plural': 'Оружие'},
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_img',
            field=models.ImageField(default='', upload_to='heroesimages/'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.CharField(max_length=200, verbose_name='Урон'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='other_properties',
            field=models.TextField(blank=True, verbose_name='Различные свойства'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type_of_damage',
            field=models.CharField(max_length=200, verbose_name='Тип урона'),
        ),
    ]
