# Generated by Django 4.1.3 on 2023-07-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_alter_weapon_weapon_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='weigth',
            new_name='weight',
        ),
    ]
