# Generated by Django 4.1.3 on 2022-12-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_hero_survival_hero_survival_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_img',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hit_dice',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
