# Generated by Django 4.1.3 on 2023-01-02 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_alter_hero_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20, 'Уровень не может быть выше 20'), django.core.validators.MinValueValidator(1, 'Уровень не может быть ниже 1')]),
        ),
    ]
