# Generated by Django 4.1.3 on 2023-07-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_alter_feature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Feature'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Spell'),
        ),
    ]
