# Generated by Django 4.1.3 on 2023-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0008_alter_hero_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='charisma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='constitution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='death_saves_failures',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='death_saves_successes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='dexterity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='intelligence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='wisdom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
