# Generated by Django 4.1.3 on 2023-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0008_alter_feature_name_alter_item_name_alter_spell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='attacks_and_spellcasting',
            field=models.ManyToManyField(blank=True, null=True, to='heroes.spell'),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='heroes.item'),
        ),
        migrations.AlterField(
            model_name='character',
            name='features_and_traits',
            field=models.ManyToManyField(blank=True, null=True, to='heroes.feature'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, null=True, to='heroes.weapon'),
        ),
    ]
